### ISSUE TITLE
关于组件文档生成方式的疑问

### ISSUE THREAD

**Issue by wdpm** [DWYW/yuumi-ui-vue#3]
很棒的基于Vue 3.x的UI库，源码非常简洁，感谢作者的无私分享。

目前这个新重构的UI库的文档中，仅有基本demo的展示用法，缺乏API文档的描述，例如：

- pros
- method
- slots
- event
- ......

之前，我也阅读过你上一个UI库 bee-ui 的源码与文档，其文档是使用人手编写的模式，示例如下，alert组件：
![Snipaste_2022-11-18_23-06-52](https://user-images.githubusercontent.com/14016242/202736865-8b7d1f18-74a4-44f9-b6fa-71d83f5b76b6.png)

这种模式虽然可行，但是缺点非常明显。
- **组件源码和组件的markdown分离，容易出现不一致**。一旦代码迭代修改，必须同时修改对应的md文档，心智负担较高。
- 工作量较大。

## 疑问/探讨
我想问下作者是否有一种更加自动化的生成API文档的模式？

根据目前个人的技术调研，基于typescript来编写组件对应的类型文件@type，将API定义于这个类型文件中：
- 组件根据@type的定义来实现，=> 源码是严格遵守@type的。
- 使用词法/语法/AST解析器来解析这个@type，=> 抽取其中的注释，生成markdown中的API章节文档。

因为@type的契约关系，实现和文档都是绝对一致的，如果不一致的话，实现会报错。而文档也能很好地自动化生成。于是，API文档的书写压力转移到了规范的@type中。

这种方式已经有一些开源UI组件这么做了。不知作者对自动化API文档生成这块，是否有其他见解？

@DWYW

**Comment by DWYW** [comment]
很高兴您能提出这个问题，由于个人精力有限，并没有去花大精力去研究自动生成API的问题，现在的API都是一边写组件一边写demo，验证个个组件的相应功能。您的宝贵意见可能会在后续的工作中考虑如何去实现。也欢迎提PR。

**Comment by DWYW** [comment]
很高兴您能提出这个问题，由于个人精力有限，并没有去花大精力去研究自动生成API的问题，现在的API都是一边写组件一边写demo，验证个个组件的相应功能。您的宝贵意见可能会在后续的工作中考虑如何去实现。也欢迎提PR。

**Comment by wdpm** [comment]
> 现在的API都是一边写组件一边写demo，验证个个组件的相应功能

这种做法非常直接，也是个人以前用过的做法。我是发觉这种做法不够规范，而且不一致的弊端非常明显。因为一旦更新了某个功能的代码，一旦忘记更新文档，就会造成不一致。

**非常理解开源项目的发展不是一件容易的事情，需要持续不断的精力投入和悉心维护**。如果以后我探索并实践论了很好的文档生成策略，我也会分享出来。

**Comment by DWYW** [comment]
感谢您的宝贵意见，我认为最好的文档就是demo，这样就可以不用专门再写单元测试，所以现在的方式暂时不会出现图示的内容。这个库的文档我也会先坚持用demo做文档。
![](https://user-images.githubusercontent.com/14016242/202736865-8b7d1f18-74a4-44f9-b6fa-71d83f5b76b6.png)

**Comment by wdpm** [comment]
> 感谢您的宝贵意见，我认为最好的文档就是demo，这样就可以不用专门再写单元测试，所以现在的方式暂时不会出现图示的内容。这个库的文档我也会先坚持用demo做文档。 ![](https://user-images.githubusercontent.com/14016242/202736865-8b7d1f18-74a4-44f9-b6fa-71d83f5b76b6.png)

实际上我不关心这个库的文档是用什么做的，我关心的只是文档自动生成的方法论，以及不断迭代进化的工程实践的工作流。
因此我一直在寻找一种更加先进的开发前端库/框架的方法论。同时也阅读了大量的前端UI库/框架的源码。
当然，demo即文档在早期incubator阶段是完全可行的，省去了很多工作量。但是，如果项目继续变大的话，可能demo就难以穷尽用法了。可能有些注意点无法通过demo来说明。

这个issue只是我的个人疑问而提问的，如果打扰到你，那我在此表示歉意。

**Comment by DWYW** [comment]
同意你的观点，技术是为了解决某些问题的。不同的阶段，需要用不同的技术解决侧重点。期待您的调研有一个好的解决方案。很希望您有后续的分享，期待中。
